---
- name: Install useful tools
  package:
    name:
      - htop
      - vim
    state: present

- name: Copy vagrant authorized keys to root
  copy:
    src: /home/vagrant/.ssh
    dest: /root/
    remote_src: yes
