---
- name: Install Libvirt package
  package:
    name:
      - libvirt-daemon-system
      - python3-libvirt
    state: present
  when: not xen_src

- include: libvirt_source.yml
  when: xen_src and build_sources

- name: Ensure libvirt group exists
  group:
    name: libvirt
    state: present

- name: Add user to libvirt group
  user:
    name: vagrant
    groups: libvirt
    append: yes

- name: Ensure libvirt daemon is started
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Install libvirt module requirements
  package:
    name: python3-lxml
    state: present

- name: Undefine default network
  community.libvirt.virt_net:
    command: undefine
    name: default
    uri: "xen:///"

- name: Redefine default network
  community.libvirt.virt_net:
    command: define
    name: default
    xml: '{{ lookup("file", "net-default.xml") }}'
    uri: "xen:///"

- name: Start default network
  community.libvirt.virt_net:
    name: default
    state: active
    autostart: yes
    uri: "xen:///"

- name: List existing storage pools
  community.libvirt.virt_pool:
    command: list_pools
    uri: "xen:///"
  register: xen_pools

- name: Define new directory pool
  community.libvirt.virt_pool:
    command: define
    name: default
    xml: '{{ lookup("file", "pool.xml") }}'
    uri: "xen:///"
  when: '"default" not in xen_pools.list_pools'

- name: Build pool
  community.libvirt.virt_pool:
    command: build
    name: default
    uri: "xen:///"
  when: '"default" not in xen_pools.list_pools'

- name: Activate pool
  community.libvirt.virt_pool:
    name: default
    state: active
    autostart: yes
    uri: "xen:///"
